### ISSUE TITLE
(Metabug) Localization of core documents

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#226]
This bug tracks smaller pieces of work that break off of #218. The languages are currently based on who we have that can do the work. If you would like to propose a language please do so. The list we currently have for localization is: 

Russian
  * [ ] [Process document](https://tc39.es/process-document/) -- probably delay this as there will be a couple more changes over the next months
  * [ ] [Code of Conduct](https://tc39.es/code-of-conduct/)
  * [ ] Jory's "how to participate" document or Allen's ["patterns for participation"](http://wirfs-brock.com/allen/files/papers/standpats-asianplop2016.pdf) 
  * [ ] [agenda topic rules](https://github.com/tc39/agendas/blob/master/template.md#agenda-topic-rules) (to be linked from the agenda, as this doesn't change much)
  * [ ] README of [How-We-Work](https://github.com/tc39/how-we-work/), with a prioritization of which documents need translations. I would propose that "how to champion", "how to give helpful feedback", and "how to write an explainer" be the first ones. Last one will be terminology as that one changes the most.

German
  * [ ] [Process document](https://tc39.es/process-document/) -- probably delay this as there will be a couple more changes over the next months
  * [ ] [Code of Conduct](https://tc39.es/code-of-conduct/)
  * [ ] Jory's "how to participate" document or Allen's ["patterns for participation"](http://wirfs-brock.com/allen/files/papers/standpats-asianplop2016.pdf) 
  * [ ] [agenda topic rules](https://github.com/tc39/agendas/blob/master/template.md#agenda-topic-rules) (to be linked from the agenda, as this doesn't change much)
  * [ ] README of [How-We-Work](https://github.com/tc39/how-we-work/), with a prioritization of which documents need translations. I would propose that "how to champion", "how to give helpful feedback", and "how to write an explainer" be the first ones. Last one will be terminology as that one changes the most.

Chinese - Simplified
  * [ ] [Process document](https://tc39.es/process-document/) -- probably delay this as there will be a couple more changes over the next months
  * [ ] [Code of Conduct](https://tc39.es/code-of-conduct/)
  * [ ] Jory's "how to participate" document or Allen's ["patterns for participation"](http://wirfs-brock.com/allen/files/papers/standpats-asianplop2016.pdf) 
  * [ ] [agenda topic rules](https://github.com/tc39/agendas/blob/master/template.md#agenda-topic-rules) (to be linked from the agenda, as this doesn't change much)
  * [ ] README of [How-We-Work](https://github.com/tc39/how-we-work/), with a prioritization of which documents need translations. I would propose that "how to champion", "how to give helpful feedback", and "how to write an explainer" be the first ones. Last one will be terminology as that one changes the most.
